<?php 
use Phalcon\Tag;
use Common\Components\Widgets\Grid;
use Common\Models\IBuyer;
 ?>


<div class="row">
    <div class="col-xs-12" style="text-align: right">
        <form id="search" action="<?=$this->url->get($base_url.'/index')?>" class="form-inline">
            <input type="text" name="name" class="input-middle" placeholder="姓名" value="<?=$vars['name']?>" />
            <input type="text" name="phone" class="input-middle" placeholder="电话" value="<?=$vars['phone']?>" />
          
            ?>
            <select name="status">
                <option value>状态</option>
                <option value="1" <?php if($vars['status']==1):?>selected<?php endif;?>>正常</option>
                <option value="-1" <?php if($vars['status']==-1):?>selected<?php endif;?>>冻结</option>
            </select>
                        
            <button id="searchBtn" type="submit" class="btn btn-info btn-sm">
                <i class="ace-icon fa fa-key bigger-110"></i>搜索
            </button>
            <button id="addBtn" type="button" class="btn btn-success btn-sm addBtn" ajax="<?=$this->url->get($base_url.'/create')?>">
                <i class="ace-icon fa fa-plus bigger-110"></i>新增
            </button>
        </form>
    </div>
    <div class="col-xs-12">
        <!-- <a href="<?=$this->url->get($base_url.'/index',['status'=>0])?>" class="btn btn-sm <?php if($vars['status']==0):?>btn-primary<?php else:?>btn-info<?php endif;?>">待审用户</a> -->
        <a href="<?=$this->url->get($base_url.'/index',['status'=>1])?>" class="btn btn-sm <?php if($vars['status']==1):?>btn-primary<?php else:?>btn-info<?php endif;?>">正式采购员</a>
        <a href="<?=$this->url->get($base_url.'/index',['status'=>-1])?>" class="btn btn-sm <?php if($vars['status']==-1):?>btn-primary<?php else:?>btn-info<?php endif;?>">冻结采购员</a>
    </div>
    <div class="col-xs-12">
    <?php
    $buttons = ['update','resetpsw','delete'];
    $grid = new Grid;
    $grid->run(array(
        'cols'=>[
            ['ID','buyer_id'],
            [IBuyer::getAttr('name'),'name'],
            [IBuyer::getAttr('phone'),'phone'],
            [IBuyer::getAttr('create_time'),'date("Y-m-d",strtotime({$o}->create_time))','function'],
            [IBuyer::getAttr('status'),'{$o}->getStatusContext({$o}->status).({$o}->status==0 ? " <a class=\"btn btn-minier btn-info audit-btn\"  data-id=\"".{$o}->buyer_id."\" href=\"javascript:void(0)\">审核</a>" : ({$o}->status>0 ? " <a class=\"btn btn-minier btn-warning freeze-btn\"  data-id=\"".{$o}->buyer_id."\" href=\"javascript:void(0)\">冻结</a>" : " <a class=\"btn btn-minier btn-info unfreeze-btn\" data-id=\"".{$o}->buyer_id."\" href=\"javascript:void(0)\">解冻</a>"))','function']
        ],
        'buttons'=>$buttons,
        'buttonsCfg'=>[
            'resetpsw'=>[
                'iconCss'=>'fa-key ',
                'type'=>'ajax',
                'url'=>'i_buyer/resetpsw',
                // 'url_param'=>'buyer_id',
                'title'=>'重置密码',
                'btnCss'=>'btn-purple resetpsw-btn'
            ],
         
        ],
        'page'=>$page,
        // 'primeData'=>'u',
        'vars'=>[
            'module'=>$module
        ]
        ));
    ?>

    </div>
</div>

<?php
$audit_url = $this->url->get($base_url.'/audit');
$refuse_url = $this->url->get($base_url.'/delete');
$freeze_url = $this->url->get($base_url.'/freeze');
$resetpsw_url = $this->url->get($base_url.'/resetpsw');
$this->assets->js['foot'][] = <<<EOT
raw::
$(function(){

    $('.audit-btn').click(function(){
        var env = this;

        layer.confirm('是否要通过此采购员的审核？',{
            btn: ['审核通过', '不通过'],
            yes:function(index, layero){
                $.get('$audit_url',{id:$(env).attr('data-id')},function(result){
                    if(result.status){
                        successMsg('操作成功'+(result.msg ? '，'+result.msg : ''));

                        layer.close(index);
                        location.reload();
                    }
                    else{
                        errorMsg('操作失败'+(result.msg ? '，'+result.msg : ''));
                    }
                });
            },
            btn2: function(index, layero){
                $.get('$refuse_url',{id:$(env).attr('data-id')},function(result){
                    if(result.status){
                        successMsg('操作成功'+(result.msg ? '，'+result.msg : ''));

                        layer.close(index);
                        location.reload();
                    }
                    else{
                        errorMsg('操作失败'+(result.msg ? '，'+result.msg : ''));
                    }
                });
            }
        });

     
    });

    $('.freeze-btn').click(function(){
        var env = this;
        layer.confirm('确定要冻结此采购员吗？', function(index){
            $.get('$freeze_url',{id:$(env).attr('data-id')},function(result){
                if(result.status){
                    successMsg('操作成功'+(result.msg ? '，'+result.msg : ''));
                }
                else{
                    errorMsg('操作失败'+(result.msg ? '，'+result.msg : ''));
                }
            });
            layer.close(index);
            location.reload();
        });
    });

    $('.unfreeze-btn').click(function(){
        var env = this;
        layer.confirm('确定要恢复此冻结采购员吗？',function(index){
            $.get('$freeze_url',{id:$(env).attr('data-id')},function(result){
                if(result.status){
                    successMsg('操作成功'+(result.msg ? '，'+result.msg : ''));
                }
                else{
                    errorMsg('操作失败'+(result.msg ? '，'+result.msg : ''));
                }
            });
            layer.close(index);
            location.reload();
        });
    });

    $('.resetpsw-btn').click(function(){
        var env = this;
        layer.confirm('确定要重置此采购员的密码吗？',function(index){
            $.get($(env).attr('ajax'),function(result){
                if(result.status){
                    successMsg('操作成功'+(result.msg ? '，'+result.msg : ''));
                }
                else{
                    errorMsg('操作失败'+(result.msg ? '，'+result.msg : ''));
                }
            });
            layer.close(index);
            location.reload();
        });
    });
});
EOT;
 ?>