<div class="page-header">
    <h1>Congratulations!</h1>
</div>

<form enctype="multipart/form-data" method="post" action="http://127.0.0.1/dao/huo/api/index.php?_url=/index/save">
	<input name="id_num" type="text"></input>
	<input name="id_card" type="file"></input>
	<input name="biz_license" type="file"></input>
	<input name="drive_license" type="file"></input>
	<input type="submit"></input>
</form>