<div class="widget-box">
	

	<div class="widget-body">
		<div class="widget-main">
			<form class="form-horizontal" role="form" id="update" method="post" action="<?=$this->url->get($base_url.'/edit')?>">
				<input type="hidden" id="update_id" name="id" value="">
				<div class="form-group">
					<label class="col-sm-3 control-label no-padding-right" for="update_name"> 参数</label>

					<div class="col-sm-9">
						<input type="text" disabled="disabled" id="update_name" name="name" placeholder="" class="col-xs-10 col-sm-5" />
					</div>
				</div>

				<div class="form-group">
					<label class="col-sm-3 control-label no-padding-right" for="update_value"> 值</label>

					<div class="col-sm-9">
						<input type="text" id="update_value" name="value" placeholder="" class="col-xs-10 col-sm-5" />
					</div>
				</div>

				<div class="form-group">
					<label class="col-sm-3 control-label no-padding-right" for="update_context">  说明</label>

					<div class="col-sm-9">
						<input type="text" id="update_context" name="context" placeholder="Text Field" class="form-control" />
					</div>
				</div>
			</form>
		</div>
	</div>
</div>