<?php 
use Phalcon\Tag;
use Common\Components\Widgets\Grid;
use Common\Models\ISpec;
 ?>


<div class="row">
    <div class="col-xs-12">
        <div class="col-xs-2">
            <div class="widget-box widget-color-green">
                <div class="widget-header">
                    <h4 class="widget-title lighter smaller">商品分类</h4>
                </div>

                <div class="widget-body">
                    <div class="widget-main padding-8">
                        <ul id="treeDemo" class="ztree"></ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-10">
            <div class="row" style="text-align:right">
                <form id="search" action="<?=$this->url->get($base_url.'/index')?>" class="form-inline">
                <?php if($vars['category_id']):?>
                    <button id="addBtn" type="button" class="btn btn-success btn-sm addBtn" ajax="<?=$this->url->get($base_url.'/create',['category_id'=>$vars['category_id']])?>">
                    <i class="ace-icon fa fa-plus bigger-110"></i>新增
                    </button>
                <?php endif;?>
                </form>

            </div>
           
            <div class="row">
                <?php
                $grid = new Grid;
                $grid->run(array(
                    'cols'=>[
                        [ISpec::getAttr('spec_name'),'spec_name'],
                        [ISpec::getAttr('specs'),'specs'],
                    ],
                    'buttons'=>['update','delete'],
                    'buttonsCfg'=>[],
                    'page'=>$page,
                    'hidePage'=>true,
                    ));
                ?>

            </div>
        </div>
        
    </div>
    
</div>


<?php 
$this->assets->css['head'][] = 'inc::js/zTree/css/zTreeStyle/zTreeStyle.css';
$this->assets->js['foot'][] = 'inc::js/zTree/js/jquery.ztree.core.js';
$this->assets->js['foot'][] = 'inc::'.$this->url->getStatic($this->url->get('admin/data/getCategoriesForZtree',['category_id'=>$vars['category_id'],'shop_id'=>$shop_id,'related_model'=>'spec']));
$this->assets->js['foot'][] = <<<EOT
raw::
var setting = {
    data: {
        simpleData: {
            enable: true
        }
    }
};
$(document).ready(function(){
    $.fn.zTree.init($("#treeDemo"), setting, zNodes);
});
EOT;
 ?>
