<?php 
use Phalcon\Tag;
use Common\Models\StatDaySale;
use Common\Models\IGoodsSpu as Spu;
use Common\Models\IGoodsSku as Sku;
?>

<div class="row">
    <div class="col-xs-12" style="text-align: right">
        <form id="search" action="<?=$this->url->get($base_url.'/index')?>" class="form-inline">  
            <select name="" id="selectCategory"></select>
            <input type="hidden" id="category_id" name="category_id" value="">
            发货日期:         
            <input type="text" name="start_day" placeholder="开始日期" class="input-small date-picker" value="<?=$vars['start_day']?>">   
            -
            <input type="text" name="end_day" placeholder="结束日期" class="input-small date-picker" value="<?=$vars['end_day']?>">       
       
            <button id="searchBtn" type="submit" class="btn btn-info btn-sm">
                <i class="ace-icon fa fa-key bigger-110"></i>搜索
            </button>
        </form>
    </div>
</div>

<div class="row">
    <div class="col-xs-12">
    <table class="table table-hover">

        <tbody>
        <?php
        foreach($stat_list as $item):?>
            <tr>
                <td width="22%">
                    <table class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th><?=Spu::getAttr('spu_name')?></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td><?=$item['spu_name']?></td>
                            </tr>
                        </tbody>
                    </table>
                </td>
                <td>
                    <table class="table table-striped table-bordered">
                        <thead>
                            <tr>

                                <th><?=Sku::getAttr('sn')?></th>
                                <th><?=Sku::getAttr('spec_info')?></th>
                            <?php foreach($days as $v): ?>
                                <th><?=substr($v,5)?></th>
                            <?php endforeach; ?>
                                <th>总计</th>
                                <th>平均</th>
                                <th>占比</th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php foreach($item['skus'] as $sku_id => $sku):?>
                            <tr>
                                <td><?=$sku['sn']?></td>
                                <td><?=$sku['spec_info']?></td>
                            <?php foreach($days as $v):?>
                                <td><?=$sku['stat'][$v]?></td>
                            <?php endforeach; ?>   
                                <td><?=$sku['total']?></td>
                                <td><?=$sku['avg']?></td>
                                <td><?=$sku['percent']?></td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                
                </td>
            </tr>
        <?php endforeach;?>
        </tbody>
    </table>
    

    </div>
</div>

<?php 
$this->assets->js['foot'][] = 'inc::'.$this->url->getStatic($this->url->get('admin/data/getCategories',null));
$this->assets->js['foot'][] = <<<EOT
raw::
$(function(){
    $('.date-picker').datepicker({
        dateFormat:'yy-mm-dd',
        autoclose: true,
        todayHighlight: true,
        maxDate:'+0 day'
    });

    var linkSelect = new LinkageSel({
        data:categories,
        select: '#selectCategory',
        head:'选择分类',
        minWidth:80,
        autoLink:false,
        loaderImg:'$loaderImg',
        defVal:[$defVal]
    });

    linkSelect.onChange(function(){
        $('#category_id').val(linkSelect.getSelectedValue());
        console.log($('#category_id').val());
    });
    
    $('#search').submit(function(){
        var start = $('input[name="start_day"]').val();
        var end = $('input[name="end_day"]').val();

        if(start){
            var start_day = start.split('-');
            var start_date = new Date(start_day[0],start_day[1],start_day[2]);
        }
        if(end){
            var end_day = end.split('-');
            var end_date = new Date(end_day[0],end_day[1],end_day[2]);
        }
        console.log(start_date);
        console.log(end_date);
        
        if(start_date && end_date){
            if(start_date>end_date){
                errorMsg("搜索的开始日期不能大于结束日期");
                return false;
            }
            
            if(end_date.getTime() - start_date.getTime() > 30*86400*1000){
                errorMsg("搜索的日期跨度不能超过30天");
                return false;
            }
        }
        
        
        
    });

});
        
EOT;
?>