<?php 
use Phalcon\Tag;
use Common\Components\Widgets\Grid;
use Common\Models\IFlashSale;
use Common\Models\IFlashSaleSpu as SaleSpu;
use Common\Models\IGoodsSpu as Spu;
 ?>

<div class="row">
    <div class="col-xs-12" style="text-align: right">
        <form id="search" action="<?=$this->url->get($base_url.'/index')?>" class="form-inline">           
            <a class="btn btn-success btn-sm" href="<?=$this->url->get($base_url.'/create')?>">
                <i class="ace-icon fa fa-plus bigger-110"></i>新增
            </a>
        </form>
    </div>
</div>
<div class="row tabs-wrapper">
    <div class="col-xs-12">
        <a href="<?=$this->url->get($base_url.'/index',['status'=>2])?>" class="btn btn-sm <?php if($vars['status']==2):?>btn-primary<?php else:?>btn-grey<?php endif;?>">进行中的抢购</a>
        <a href="<?=$this->url->get($base_url.'/index',['status'=>1])?>" class="btn btn-sm <?php if($vars['status']==1):?>btn-primary<?php else:?>btn-grey<?php endif;?>">未开始的抢购</a>
        <a href="<?=$this->url->get($base_url.'/index',['status'=>3])?>" class="btn btn-sm <?php if($vars['status']==3):?>btn-primary<?php else:?>btn-grey<?php endif;?>">已结束的抢购</a>
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
    <table class="table table-striped table-bordered table-hover dataTable">
        <thead>
            <!-- <tr>
                <th><?=IFlashSale::getAttr('name')?></th>
                <th><?=Spu::getAttr('spu_name')?></th>
                <th><?=Spu::getAttr('price')?></th>
                <th><?=SaleSpu::getAttr('sale_price')?></th>
                <th><?=SaleSpu::getAttr('sale_stock')?></th>
                <th>操作</th>
            </tr> -->
        </thead>
        <tbody>
        <?php foreach($page->items as $Item):?>
            <tr>
                <td width="20%">
                    <?=$Item->sale_name?>
                    <p><?=$Item->start_time?>至<?=$Item->end_time?></p>
                    <?php if($Item->status==3):?>
                    <p>结束于：<?=$Item->finish_time?></p>
                    <?php endif;?>
                </td>
                <td>
                    <table class="table table-striped table-bordered dataTable">
                        <thead>
                            <tr>
                                <th colspan="2" width="50%"><?=Spu::getAttr('spu_name')?></th>
                                <th width="15%"><?=Spu::getAttr('price')?></th>
                                <th width="10%"><?=SaleSpu::getAttr('sale_price')?></th>
                                <th width="10%"><?=SaleSpu::getAttr('sale_stock')?></th>
                                <th width="15%"><?=SaleSpu::getAttr('per_limit')?></th>
                                <th width="10%"><?=Spu::getAttr('status')?></th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php foreach($Item->spus as $SaleSpu): ?>
                            <tr>
                                <td width="15%"><img class="thumb" src="<?=$SaleSpu->Spu->getFmtCover()?>"></td>
                                <td><?=$SaleSpu->Spu->spu_name?></td>
                                <td><?=fmtMoney($SaleSpu->Spu->price)?></td>
                                <td><?=fmtMoney($SaleSpu->sale_price)?></td>
                                <td><?=$SaleSpu->sale_stock?></td>
                                <td><?=$SaleSpu->per_limit?></td>
                                <td><?=Spu::getStatusContext($SaleSpu->Spu->status)?></td>
                            </tr>
                        <?php endforeach;?>
                        </tbody>
                    </table>
                </td>
                <td>
                    <?=$Item->getStatusContext($Item->status)?>
                </td>
                <td>
                <?php if($Item->status==1):?>
                    <a title="更新" class="btn btn btn-minier btn-yellow" container="update" href="/admin/i_flash_sale/update?id=<?=$Item->sale_id?>">
                        <i class="ace-icon fa fa-pencil-square-o bigger-130"></i> 更新
                    </a>
                <?php endif;?>
                <?php if($Item->status!=3):?>
                    <br><br>
                    <button type="button" title="结束" class="btn btn btn-minier btn-danger finish-btn" container="update" ajax="/admin/i_flash_sale/finish?id=<?=$Item->sale_id?>">
                        <i class="ace-icon fa fa-pause-circle-o bigger-130"></i> 结束
                    </button>
                <?php endif;?>
                </td>
                
                
            </tr>
        <?php endforeach;?>
        </tbody>
    </table>
    

    </div>
</div>
<?php if($page->total_items):?>
<div class="row pager">
    <div class="col-xs-12">
        <div class="dataTables_paginate paging_bootstrap">
            <ul class="pagination">
               
                <?php $vars['p'] = 1;?>
                <li class="prev <?php if($page->current<=1):?>disabled<?php endif;?>"><a href="<?php echo $this->url->get($module.'/'.$this->dispatcher->getControllerName().'/index',$vars)?>"><i class="fa fa-angle-double-left"></i></a></li>
                <?php $vars['p'] = $page->current-1 ?>
                <li class="prev <?php if($page->current<=1):?>disabled<?php endif;?>"><a href="<?php echo $this->url->get($module.'/'.$this->dispatcher->getControllerName().'/index',$vars)?>"><i class="fa fa-angle-left"></i></a></li>
                <?php
                $num = 3;
                if($page->current-$num<=1){
                    $start = 1 ;
                }
                else{
                    $start = $page->current - $num;
                }

                if($page->current+$num>=$page->total_pages){
                    $end = $page->total_pages;
                }
                else{
                    $end = $page->current + $num;
                }

                $p = $start;
                $vars = $this->view->vars;
                //var_dump($vars);exit;
                $vars['menu'] = $this->request->getQuery('menu');
                while($p<=$end){
                    $vars['p'] = $p;
                ?>
                <li class="<?php if($page->current==$p):?>active<?php endif;?>"><a href="<?php echo $this->url->get($module.'/'.$this->dispatcher->getControllerName().'/index',$vars)?>"><?=$p?></a></li>
                <?php
                    $p++;
                }
                ?>
                <?php $vars['p'] = $page->total_pages;?>
                <li class="next <?php if($page->current>=$page->total_pages):?>disabled<?php endif;?>"><a href="<?php echo $this->url->get($module.'/'.$this->dispatcher->getControllerName().'/index',$vars)?>"><i class="fa fa-angle-double-right"></i></a></li>
                <?php $vars['p'] = $page->current+1;?>
                <li class="next <?php if($page->current>=$page->total_pages):?>disabled<?php endif;?>"><a href="<?php echo $this->url->get($module.'/'.$this->dispatcher->getControllerName().'/index',$vars)?>"><i class="fa fa-angle-right"></i></a></li>
                
            </ul>
             <div class="page_info"><?php if(!$hidePageStat):?><span>共有<?=$page->total_pages?>页，总计<?=$page->total_items?>条</span><?php endif;?></div>
        </div>
    </div>
</div>
<?php endif;?>
<?php
$freeze_url = $this->url->get($base_url.'/freeze');
$resetpsw_url = $this->url->get($base_url.'/resetpsw');
$this->assets->js['foot'][] = 'inc::back/js/my.grid.js';
$this->assets->js['foot'][] = <<<EOT
raw::
$(function(){
    $('.grid-wrapper').hide();
    
    $('.finish-btn').click(function(){
        var env = this;
        layer.confirm('确定要结束此抢购吗？', function(index){
            $.get($(env).attr('ajax'),function(result){
                if(result.status){
                    successMsg('操作成功'+(result.msg ? '，'+result.msg : ''));
                    location.reload();
                }
                else{
                    errorMsg('操作失败'+(result.msg ? '，'+result.msg : ''));
                }
            });
            layer.close(index);
            
        });
    });
});
EOT;
 ?>