<?php 
use Phalcon\Tag;
use Common\Components\Widgets\Grid;
use Common\Models\Comment;
use Common\Models\ServiceObject;
?>

<div class="row">
    <div class="col-xs-12" style="text-align: right">
        <form id="search" action="<?=$this->url->get($module.'/comment/index')?>" class="form-inline">
            <?php if($this->auth->getRole()==1):?>
            <?php
            Tag::setDefault('sobj_id',$this->request->getQuery('sobj_id'));
            $service_objects = ServiceObject::find();
            echo Tag::select(array(
                    "sobj_id",
                    $service_objects,
                    "using" => array("service_object_id", "name"),
                    "useEmpty" => true
                ));
            ?>
            <button id="searchBtn" type="submit" class="btn btn-info btn-sm">
                <i class="ace-icon fa fa-key bigger-110"></i>搜索
            </button>
            <?php endif;?>
        </form>
    </div>
    <div class="col-xs-12">
    <div class="row">
    <?php foreach($page->items as $v):?>
        <div class="comment_item">
            <div class="comment_content">
                <div class="itemdiv dialogdiv" id="comment_<?=$v->comment_id?>">
                    <div class="user"><img src="<?php if($v->user_id and $v->user->head_pic):?><?=$v->user->head_pic?><?php elseif($v->sns_user_id and $v->wxuser->head_img_url):?><?=$v->wxuser->head_img_url?><?php else:?>/back/avatars/default1.png<?php endif;?>"></div>
                    <div class="body" >
                        <div class="time">                            
                            <i class="ace-icon fa fa-clock-o"></i>
                            <span class="blue"><?=$v->create_date?></span>                            
                        </div>
                        <div class="status">
                            <span class="label label-<?php if(1==$v->status):?>warning<?php elseif(10==$v->status):?>success<?php elseif(-1==$v->status):?>danger<?php endif;?> arrowed-right arrowed-in"><?=$v->getStatusContext($v->status)?></span>
                        </div>
                        <div class="name"><?php
                        if($v->user_id){
                            echo $v->user->username;
                        }elseif($v->sns_user_id){
                            echo '<img src="'.$this->url->get('back/images/wx_mini.png').'"> '.$v->wxuser->nickname;
                        }else{
                            echo '匿名访客';
                        }
                        ?></div>
                        <div class="text"><?=$v->content?></div>
                        <div class="target">相关内容：
                        <?php 
                        if($v->content_type==1) 
                            echo Tag::linkTo($this->url->get($module.'/guide_point/index',['id'=>$v->content_id,'menu_id'=>$v->point->menu_id,'sub_menu_id'=>$v->point->sub_menu_id]),$v->point->guide_name);
                        elseif($v->content_type==2)
                            echo Tag::linkTo($this->url->get($module.'/article/index',['id'=>$v->content_id,'menu_id'=>$v->article->menu_id,'sub_menu_id'=>$v->article->sub_menu_id]),$v->article->title);
                        elseif($v->content_type==3)
                            echo Tag::linkTo($this->url->get($module.'/human/index',['id'=>$v->content_id,'menu_id'=>$v->human->menu_id,'sub_menu_id'=>$v->human->sub_menu_id]),$v->human->name);
                        elseif($v->content_type==4)
                            echo $v->sobj->name;
                        ?></div>
                        <div class="tools">
                        <?php if($v->status!=10):?>
                            <a title="审核通过" class="btn btn-xs btn-info publishBtn" href="javascript:void(0)" i="comment_<?=$v->comment_id?>" ajax="<?=$this->url->get("admin/comment/publish",["id"=>$v->comment_id])?>">
                                <i class="icon-only ace-icon fa fa-check"></i>
                            </a>
                        <?php endif;?>
                        <?php if($v->status==10):?>
                            <a title="取消审核" class="btn btn-xs btn-warning unPublishBtn" href="javascript:void(0)" i="comment_<?=$v->comment_id?>" ajax="<?=$this->url->get("admin/comment/unPublish",["id"=>$v->comment_id])?>">
                                <i class="icon-only ace-icon fa fa-ban"></i>
                            </a>
                        <?php endif;?>
                        <?php if($v->status>0):?>
                            <a title="删除" class="btn btn-xs btn-danger deleteBtn" href="javascript:void(0)" i="comment_<?=$v->comment_id?>" ajax="<?=$this->url->get("admin/comment/delete",["id"=>$v->comment_id])?>">
                                <i class="icon-only ace-icon fa fa-times"></i>
                            </a>
                            <a title="回复" class="btn btn-xs btn-success replyBtn" href="javascript:void(0)" i="comment_<?=$v->comment_id?>" ajax="<?=$this->url->get("admin/reply/form",["comment_id"=>$v->comment_id])?>">
                                <i class="icon-only ace-icon fa fa-reply"></i>
                            </a>
                        <?php endif;?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="scroll-content" <?php /*?>style="max-height: 300px; overflow:auto;"<?php */?>>
                <div class="replies">
                    <?php if($v->replies):?>
                    <?php foreach ($v->replies as $r) :?>
                    <div class="itemdiv dialogdiv" id="reply_<?=$r->reply_id?>">
                        <div class="user">
                            <img src="/back/avatars/default2.jpg">
                        </div>
                        <div class="body">
                            <div class="time">
                                <i class="ace-icon fa fa-clock-o"></i>
                                <span class="blue"><?=$r->create_date?></span>
                            </div>
                            <div class="status">
                            <?php /*?>
                                <span class="label label-<?php if(1==$r->status):?>warning<?php elseif(10==$r->status):?>success<?php elseif(-1==$r->status):?>danger<?php endif;?> arrowed-right arrowed-in"><?=$r->getStatusContext($r->status)?></span>
                            <?php */?>
                            </div>
                            <div class="name">
                            <?php
                            if($r->is_official){
                                echo '官方 '.($r->admin_id ? $r->admin->username : '');
                            }
                            else{
                                if($r->user_id){
                                    echo $r->user->username;
                                }elseif($r->sns_user_id){
                                    echo $r->wxuser->nickname;
                                }else{
                                    echo '匿名访客';
                                }
                            }
                            
                            ?></div>
                            <div class="text" style="min-height:10px"><?=$r->reply_connent?></div>
                            <div class="tools">
                            <?php if($r->status!=10):?>
                                <a class="btn btn-xs btn-info publishBtn" href="javascript:void(0)" i="reply_<?=$r->reply_id?>" ajax="<?=$this->url->get("admin/reply/publish",["id"=>$r->reply_id])?>">
                                    <i class="icon-only ace-icon fa fa-check"></i>
                                </a>
                            <?php endif;?>
                            <?php if($r->status>0):?>
                                <a class="btn btn-xs btn-info deleteBtn" href="javascript:void(0)" i="reply_<?=$r->reply_id?>" ajax="<?=$this->url->get("admin/reply/delete",["id"=>$r->reply_id])?>">
                                    <i class="icon-only ace-icon fa fa-times"></i>
                                </a>
                            <?php endif;?>
                            </div>
                        </div>
                    </div>
                    <?php endforeach;?>
                    <?php endif;?>
                    
                </div>
            </div>
        </div>
    <?php endforeach;?>
    </div>
    <div class="row">
            <div class="col-xs-6">
                <div class="dataTables_info" id="bottomBtns">
                
                </div>
            </div>
            <div class="col-xs-6">
                <div class="dataTables_paginate paging_bootstrap">

                    <ul class="pagination">
                        <li class="page_info"><span>共有<?=$page->total_pages?>页，总计<?=$page->total_items?>条</span></li>
                        <?php $vars['p'] = 1;?>
                        <li class="prev <?php if($page->current<=1):?>disabled<?php endif;?>"><a href="<?php echo $this->url->get($this->module.'/'.$this->dispatcher->getControllerName().'/index',$vars)?>"><i class="fa fa-angle-double-left"></i></a></li>
                        <?php $vars['p'] = $page->current-1 ?>
                        <li class="prev <?php if($page->current<=1):?>disabled<?php endif;?>"><a href="<?php echo $this->url->get($this->module.'/'.$this->dispatcher->getControllerName().'/index',$vars)?>"><i class="fa fa-angle-left"></i></a></li>
                        <?php
                        $num = 3;
                        if($page->current-$num<=1){
                            $start = 1 ;
                        }
                        else{
                            $start = $page->current - $num;
                        }

                        if($page->current+$num>=$page->total_pages){
                            $end = $page->total_pages;
                        }
                        else{
                            $end = $page->current + $num;
                        }

                        $p = $start;
                        $vars = $this->view->vars;
                        $vars['menu'] = $this->request->getQuery('menu');
                        while($p<=$end){
                            $vars['p'] = $p;
                        ?>
                        <li class="<?php if($page->current==$p):?>active<?php endif;?>"><a href="<?php echo $this->url->get($this->module.'/'.$this->dispatcher->getControllerName().'/index',$vars)?>"><?=$p?></a></li>
                        <?php
                            $p++;
                        }
                        ?>
                        <?php $vars['p'] = $page->current+1;?>
                        <li class="next"><a href="<?php echo $this->url->get($this->module.'/'.$this->dispatcher->getControllerName().'/index',$vars)?>"><i class="fa fa-angle-right"></i></a></li>
                        <?php $vars['p'] = $page->total_pages;?>
                        <li class="next"><a href="<?php echo $this->url->get($this->module.'/'.$this->dispatcher->getControllerName().'/index',$vars)?>"><i class="fa fa-angle-double-right"></i></a></li>
                        
                    </ul>
                    
                </div>
            </div>
        </div>

    </div>
</div>

<?php
$this->assets->js['foot'][] = <<<EOT
raw::
\$(function(){
    var deleted_status = '<span class="label label-danger arrowed-right arrowed-in">删除</span>';
    var pendding_status = '<span class="label label-warning arrowed-right arrowed-in">待审</span>';
    var published_status = '<span class="label label-success arrowed-right arrowed-in">公开</span>';

    \$( ".deleteBtn[ajax]" ).on('click', function(e) {
        if(confirm('确定要删除此条信息吗？')){
            \$.post(\$(this).attr('ajax'),{id:\$(this).attr('data-id')},function(result){
                if(result.status==1){
                    \$('#'+result.item+' div.status').html(deleted_status);
                    successMsg(result.msg);
                }
                else{
                    errorMsg(result.msg);
                }
            })
        }
    });

    \$( ".publishBtn[ajax]" ).on('click', function(e) {
        if(confirm('确定要公开此条信息吗？')){
            \$.post(\$(this).attr('ajax'),{id:\$(this).attr('data-id')},function(result){
                if(result.status==1){
                    \$('#'+result.item+' div.status').html(published_status);
                    successMsg(result.msg);                    
                }
                else{
                    errorMsg(result.msg);
                }
            })
        }
    });

    \$( ".unPublishBtn[ajax]" ).on('click', function(e) {
        if(confirm('确定要撤销此信息的公开状态吗？')){
            \$.post(\$(this).attr('ajax'),{id:\$(this).attr('data-id')},function(result){
                if(result.status==1){
                    \$('#'+result.item+' div.status').html(pendding_status);
                    successMsg(result.msg);                    
                }
                else{
                    errorMsg(result.msg);
                }
            })
        }
    });
    
    \$( ".replyBtn" ).on('click', function(e) {
        \$.get($(this).attr('ajax'),function(result){
            if(result.status==1){
                \$('#container').html(result.data);
                var dialog = \$('#container').dialog({
                    modal:true,
                    title:"<div class='widget-header widget-header-small'><h4 class='smaller'><i class='ace-icon fa fa-check'></i> 回复</h4></div>",
                    title_html:true,
                    width:700,
                    height:'auto',
                    buttons:[
                        {
                            text: "取消",
                            "class" : "btn btn-xs",
                            click: function() {
                                $( this ).dialog( "close" ); 
                            } 
                        },
                        {
                            text: "提交",
                            "class" : "btn btn-primary btn-xs",
                            click: function() {

                                var _this = this;

                                $.post($('#container form').attr('action'),$('#container form').serialize(),function(result){
                                    if(result.status==1){
                                        successMsg(result.msg);
                                        $(_this).dialog("close"); 

                                        location.reload();
                                    }
                                    else{
                                        errorMsg(result.msg);
                                        $(_this).dialog("close"); 
                                        
                                    }
                                });

                            } 
                        }
                    ]
                });
            }
            else{
                errorMsg(result.msg);
            }
        })
    });
});
EOT;


?>
