<div class="widget-box">
	

	<div class="widget-body">
		<div class="widget-main">
			<form class="form-horizontal" role="form" id="update" method="post" action="<?=$this->url->get($base_url.'/edit')?>">
				<input type="hidden" id="update_id" name="id" value="">
				<div class="form-group">
					<label class="col-sm-3 control-label no-padding-right" for="update_name"> 标识</label>

					<div class="col-sm-9">
						<input type="text" name="name" placeholder="" class="col-xs-10 col-sm-5" />
					</div>
				</div>

				<div class="form-group">
					<label class="col-sm-3 control-label no-padding-right" for="update_name"> 说明</label>

					<div class="col-sm-9">
						<input type="text" name="intro" placeholder="" class="col-xs-10 col-sm-5" />
					</div>
				</div>

			</form>
		</div>
	</div>
</div>