<?php 
use Phalcon\Tag;
use Common\Components\Widgets\Grid;
use Common\Models\ICsSession;
 ?>

<div class="row">
    <div class="col-xs-12">
        <form id="msg">
            <div class="form-actions">
                <div class="input-group">
                    <input type="hidden" id="" name="cs_session_id" value="<?=$vars['cs_session_id']?>">
                    <input placeholder="输入消息 ..." type="text" class="form-control" name="content" />
                    <span class="input-group-btn">
                        <button class="btn btn-sm btn-success no-radius" id="imgBtn" type="button">
                            <i class="ace-icon fa fa-image"></i>
                            发送图片
                        </button>
                        <button class="btn btn-sm btn-info no-radius" id="msgBtn" type="submit">
                            <i class="ace-icon fa fa-share"></i>
                            发送
                        </button>
                    </span>
                </div>
            </div>
        </form>
        <div class="dialogs cs-msgs" id="msgListContainer">
           

        </div>

        <!-- /section:pages/dashboard.conversations -->
        
         
        
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
        <div class="col-xs-6">
            <form id="searchForm" class="form-inline" style="margin:20px 0"> 
                <input type="hidden" id="" name="cs_session_id" value="<?=$vars['cs_session_id']?>">
                <!-- <input type="text" name="keyword" class="input-middle" placeholder="关键词" value="" />
                
                <button id="searchBtn" type="submit" class="btn btn-info btn-sm">
                    <i class="ace-icon fa fa-key bigger-110"></i>搜索
                </button> -->
            </form>
            <input type="hidden" name="cs_msg_id" value="" />
        </div>
        <div class="col-xs-6">
            <div style="text-align:right">
                <ul class="pagination" id="pageContainer"></ul>
            </div>
        </div>
    </div>
    
</div>

<script id="msgList" type="text/x-jsrender">
<div class="itemdiv dialogdiv">
    <div class="user">
        {^{if admin_id}}
        <img src="<?=$config->params->staticsPath?>back/avatars/default2.jpg" />
        {{else}}
        {^{if user_avatar}}
        <img src="{{:user_avatar}}" />
        {{else}}
        <img src="<?=$config->params->staticsPath?>back/avatars/default1.png" />
        {{/if}}
        
        {{/if}}
    </div>

    <div class="body">
        <div class="time">
            <i class="ace-icon fa fa-clock-o"></i>
            <span class="green">{^{:create_time}}</span>
        </div>

        <div class="name">
            <a href="#">{^{if admin_id}}{^{:admin_name}}{{/if}} {^{if user_id}}{^{:user_name}}{{/if}}</a>
        </div>
        <div class="text">
        {^{if content_type=='image'}}
            <a href="{{:content}}" data-rel="colorbox">
                <img class="thumb" src="{{:content}}">
            </a>
        {{/if}}
        {^{if content_type=='audio'}}
            <audio controls>
                <source src="{{:content}}" type="audio/mpeg">
                您的浏览器不支持音频播放
            </audio>
        {{/if}}
        {^{if content_type=='text'}}
            {^{:content}}
        {{/if}}
        </div>

        <div class="tools">
        </div>
    </div>
</div>
</script>
<?php
$url = $this->url->get($module.'/i_cs_msg/query');
$create_url = $this->url->get($module.'/i_cs_msg/create');
$upload_url = $this->url->get($module.'/upload/image',["field_name"=>'file','dir'=>'cs']);;
$this->assets->js['foot'][] = "inc::js/SimpleAjaxUploader.min.js";
$this->assets->js['foot'][] = "inc::js/jquery.twbsPagination.min.js";
$this->assets->js['foot'][] = <<<EOT
raw::

var url = '$url';
var create_url = '$create_url';
var upload_url = '$upload_url';
var timer = null;
var list = [];
function getList(p,params){
    // console.log(params);
    showAjaxLoading = false;
    params.p = p;
    $.get(url+'?'+Math.random(),params,function(result){
        $('input[name="cs_msg_id"]').val(result.data.cs_msg_id);
        var length = result.data.list.length;
        
        if(params.cs_msg_id){
            $.each(result.data.list,function(i,v){
                $.observable(list).insert(v);
            });
            if(result.data.list.length){
                scrollTop();
            }
            
        }
        else{
            // console.log(result.data.list);
            list = result.data.list;
            var tpl = $.templates("#msgList"); 
            tpl.link("#msgListContainer",list);
            page(result.data.total_pages,p);

            scrollTop();
        }

        if(p<=1 && !timer){
            timer = setInterval(function(){
                getList(1,{
                    cs_session_id:result.data.cs_session_id,
                    cs_msg_id:$('input[name="cs_msg_id"]').val()
                });
            },2000);
        }
        
        if(p>1){
            clearInterval(timer);
            timer = null;
        }

        initMsg();
        
    });     
}
var getSearchParams = function(){
	var params = {
		cs_session_id:$('#searchForm input[name="cs_session_id"]').val(),
		keyword:$('#searchForm input[name="keyword"]').val(),
	}
	return params;
}
var page = function(totalPages,p){
	totalPages = totalPages ? totalPages :1;
	p = p ? parseInt(p) :1;
	$('#pageContainer').twbsPagination('destroy');
	$('#pageContainer').twbsPagination({
		totalPages: totalPages,
		first:'<<',
		prev:'<',
		next:'>',
		last:'>>',
		// totalPages:1,
		startPage:p,
		visiblePages: 5,
		initiateStartPageClick:false,
		onPageClick: function (event, p) {
			getList(p,getSearchParams());
		}
	});
}

function scrollTop(){
    // console.log($('#msgBtn').offset().top);
    $('body,html').animate({scrollTop:100}, 300);
    // $('body,html').scrollTop(10);
}

function initMsg(){
    $('[data-rel="colorbox"]').colorbox({
        maxWidth:'80%',
        maxHeight:'80%',
        close:''
    });
}

$(function(){

    getList(1,{cs_session_id:$('#searchForm input[name="cs_session_id"]').val()});

    $('#msg').submit(function(){

        clearInterval(timer);
        timer = null;

        $.post(create_url,$(this).serialize(),function(result){
            if(result){
                $('#msg input[name="content"]').val('');
                
                getList(1,{
                    cs_session_id:$('#msg input[name="cs_session_id"]').val(),
                    // cs_msg_id:$('input[name="cs_msg_id"]').val()
                });

                scrollTop();
                
            }
            else{
                errorMsg('发送失败');
                location.reload();
            }
        });
        return false;
    });

    var sizeBox = document.getElementById('sizeBox'); // container for file size info

    var uploader = new ss.SimpleUpload({
        button: 'imgBtn', // file upload button
        url: upload_url, // server side handler
        name: 'file', // upload parameter name        
        //progressUrl: 'uploadProgress.php', // enables cross-browser progress support (more info below)
        responseType: 'json',
        allowedExtensions: ['jpg', 'jpeg', 'png', 'gif'],
        maxSize: 4096, // kilobytes
        hoverClass: 'ui-state-hover',
        focusClass: 'ui-state-focus',
        disabledClass: 'ui-state-disabled',
        onSubmit: function(filename, extension) {
            this.setFileSizeBox(sizeBox); // designate this element as file size container
        },         
        onComplete: function(filename, response) {
            if(response.status=='success'){
                var data = {
                    cs_session_id:$('#msg input[name="cs_session_id"]').val(),
                    content:response.url,
                    content_type:'image',
                    width:response.width,
                    height:response.height,
                };
                $.post(create_url,data,function(result){
                    if(result){
                        $('#msg input[name="content"]').val('');
                        
                        getList(1,{
                            cs_session_id:$('#msg input[name="cs_session_id"]').val(),
                        });
        
                        scrollTop();
                        
                    }
                    else{
                        errorMsg('发送失败');
                        location.reload();
                    }
                });
            }
            else{
                errorMsg('图片发送失败');
            }
            
        }
    });        

    
});
EOT;
?>