<?php
use Common\Models\SAclRole;
use Phalcon\Tag;
?>
<div class="widget-box">

	<div class="widget-body">
		<div class="widget-main">
			<form class="form-horizontal ajax-form" role="form" id="update" method="post" action="<?=$this->url->get($base_url.'/'.($M->id?'update':'create'))?>">
				<input type="hidden" id="update_id" name="id" value="<?=$M->id?>">
				<!-- <div class="form-group">
					<label class="col-sm-3 control-label no-padding-right" for="update_name"> <?=SAclRole::getAttr('name')?></label>
				
					<div class="col-sm-9">
						<input type="text" name="name" placeholder="" class="col-xs-10 col-sm-5" value="<?=$M->name?>" />
						<div class="help-inline">角色标识长度在2-15个字符</div>
					</div>
				</div> -->

				<div class="form-group">
					<label class="col-sm-3 control-label no-padding-right" for="update_name"> <?=SAclRole::getAttr('intro')?></label>

					<div class="col-sm-9">
						<input type="text" name="intro" placeholder="" class="col-xs-10 col-sm-5" value="<?=$M->intro?>" />
						<div class="help-inline">名称长度在2-15个字符</div>
					</div>
				</div>
			<?php /*
				<div class="form-group">
					<label class="col-sm-3 control-label no-padding-right" for="update_name"> <?=SAclRole::getAttr('school_flag')?></label>

					<div class="col-sm-9">
						<p><input type="checkbox" name="school_flag" value="1" <?php if($M->school_flag):?>checked="checked"<?php endif;?> /></p>
					</div>
				</div>

			*/ ?>
				

			</form>
		</div>
	</div>
</div>

<script type="text/javascript">
	$(function(){
		ajaxForm();
	});
</script>