<?php
use Common\Models\ILabel;
use Phalcon\Tag;
?>
<div class="widget-box">
	
	<div class="widget-body">
		<div class="widget-main">
			<form class="form-horizontal ajax-form" role="form" id="update" method="post" action="<?=$this->url->get($base_url.'/'.($M->push_id?'update':'create'))?>">
				<input type="hidden" id="" name="push_id" value="<?=$M->push_id?>">

				
				<div class="form-group">
					<label class="col-sm-3 control-label no-padding-right" for=""><span class="required">*</span> <?=$M->getAttr('content')?></label>

					<div class="col-sm-9">
                        <textarea name="content" id="" rows="5" class="col-md-10"><?=$M->content?></textarea>
					</div>
				</div>

				
			</form>
		</div>
	</div>
</div>
<script type="text/javascript">
	$(function(){
		ajaxForm();
	});
</script>