<?php
use Common\Models\ICoupon;
use Common\Models\IUser;
use Common\Models\IUserLevel;
use Phalcon\Tag;

?>
<div class="widget-box">
	
	<div class="widget-body">
		<div class="widget-main">
			<form class="form-horizontal" id="couponForm" method="post" action="<?=$this->url->get($base_url.'/'.($M->coupon_id?'update':'create'))?>"  enctype="multipart/form-data">
				<input type="hidden" name="coupon_id" value="<?=$M->coupon_id?>">

				
				
				<div class="form-group">
					<label class="col-sm-3 control-label no-padding-right" for=""><span class="required">*</span> <?=$M->getAttr('sn')?></label>

					<div class="col-sm-9">
						<p><?=$M->sn?></p>
						<input type="hidden" name="sn" value="<?=$M->sn?>">
					</div>
				</div>

				<div class="form-group">
					<label class="col-sm-3 control-label no-padding-right" for=""><span class="required">*</span> <?=$M->getAttr('coupon_name')?></label>

					<div class="col-sm-9">
						<input type="text" name="coupon_name" placeholder="" class="col-xs-10 col-sm-5" value="<?=$M->coupon_name?>" />
					</div>
				</div>

				<div class="form-group">
					<label class="col-sm-3 control-label no-padding-right" for=""><span class="required">*</span> <?=$M->getAttr('amount')?></label>

					<div class="col-sm-9">
						<input type="text" name="amount" placeholder="" class="col-xs-3 col-sm-2 input-sm" value="<?=$M->amount?>" /> <p>元</p>
					</div>
				</div>

				
				<div class="form-group">
					<label class="col-sm-3 control-label no-padding-right" for=""><span class="required">*</span> 有效期</label>

					<div class="col-sm-9">
						<input type="text" name="start_time" placeholder="" class="date-picker" value="<?=$M->start_time?>" />
						至
						<input type="text" name="end_time" placeholder="" class="date-picker" value="<?=$M->end_time?>" />
					</div>
				</div>

				<div class="form-group">
					<label class="col-sm-3 control-label no-padding-right" for=""> 使用限制</label>

					<div class="col-sm-9">
						<div>
							<p class="pull-left">满</p> <input type="text" name="min_limit" placeholder="" class="col-xs-3 col-sm-1 input-sm" value="<?=$M->min_limit?>" /> <p class="pull-left">可用</p>							
						</div>
					<?php
					if($conf['enable_vip_rebate']):
					?>
						<div class="clear"></div>
						<div>

							<input type="checkbox" class="ace ace-checkbox-2" id="withRebate" name="with_rebate" />
							<label class="lbl" for="withRebate"><?=$M->getAttr('with_rebate')?> </label>
							
							<input type="checkbox" class="ace ace-checkbox-2" id="withDiscount" name="with_discount" />
							<label class="lbl" for="withDiscount"><?=$M->getAttr('with_discount')?> </label>
						</div>
					</div>
					<?php
					endif;
					?>
				</div>

				<div class="form-group">
					<label class="col-sm-3 control-label no-padding-right" for=""><span class="required">*</span> 适用人群</label>

					<div class="col-sm-9" style="padding-top:5px;">
						<?php foreach(IUserLevel::find() as $Level):?>
						<div>
							<input type="checkbox" class="ace ace-checkbox-2" id="level<?=$Level->level_id?>" name="level[]" value="<?=$Level->level_id?>" />
							<label class="lbl" for="level<?=$Level->level_id?>"><?=$Level->level_name?> </label>
						</div>						
						<?php endforeach;?>
						<div>
							<input type="checkbox" class="ace ace-checkbox-2" id="specialUsers" name="special_users" />
							<label class="lbl" for="specialUsers">特定会员 </label>
						</div>	
						<div id="specialUsersBox" style="padding-top:10px; display:none;">
							<button type="button" class="btn btn-sm btn-purple" id="chooseUserBtn">手动选择发放会员</button>
							<div id="chosenUserListContainer" style="margin-top:10px"></div>
						</div>
						
					</div>
				</div>

				<div class="clearfix form-actions">
					<div class="col-md-offset-4 col-md-8">
						<button class="btn btn-info" type="submit">						
						<i class="ace-icon fa fa-check bigger-110"></i>
						提交
						</button>						
					</div>
				</div>
			</form>
		</div>
	</div>
</div>

<div id="searchFormContainer" style="display:none">
	<div class="widget-box">
    
	    <div class="widget-body">
	        <div class="widget-main">
	            <form id="searchForm" action="<?=$this->url->get($base_url.'/index')?>" class="form-inline">   
	            	
		            <?php
		            echo Tag::select([
		            	'level_id',
		            	IUserLevel::find(),
		            	'using'=>['level_id','level_name'],
		            	'useEmpty'=>true,
		            	'emptyText'=>'全部会员'
		            ]);
		            ?>         
		            <input type="email" name="email" class="input-middle" placeholder="邮箱" value="" />
		            <input type="text" name="phone" class="input-middle" placeholder="手机号码" value="" />
		            <button id="searchBtn" type="submit" class="btn btn-info btn-sm">
		                <i class="ace-icon fa fa-key bigger-110"></i>搜索
		            </button>
		        </form>
	            <input type="hidden" id="chosenUserId" value="">
	            <input type="hidden" id="chosenName" value="">
	            <input type="hidden" id="chosenIdNum" value="">
	        </div>
	    </div>
	</div>
	<div class="row" >
	    <div class="col-xs-12" id="spuListContainer"></div>
	    <div class="paginationContainer">
	    	<ul class="pagination" id="pageContainer"></ul>
	    </div>
	</div>
</div>

<script id="spuList" type="text/x-jsrender">
	<table class="table table-striped table-bordered table-hover">
		<thead>
			<tr>
				<th></th>
				<th><?=IUser::getAttr('user_id')?></th>
				<th><?=IUser::getAttr('name')?></th>
				<th><?=IUser::getAttr('phone')?></th>
			</tr>
		</thead>
		<tbody>
		{^{for list}}
			<tr>
				<td>
					<label>
						<input name="user" type="radio" class="ace" data-link="value{:user_id}">
						<span class="lbl"></span>
					</label>					
				</td>
				<td>{^{:user_id}}</td>
				<td>{^{:name}}</td>
				<td>{^{:phone}}</td>
			</tr>
		{{/for}}
		</tbody>
		
	</table>
</script>

<script id="chosenUserList" type="text/x-jsrender">
	<table class="table table-striped table-bordered table-hover">
		<thead>
			<tr>
				<th><?=IUser::getAttr('user_id')?></th>
				<th><?=IUser::getAttr('name')?></th>
				<th><?=IUser::getAttr('phone')?></th>
			</tr>
		</thead>
		<tbody>
		{^{for list}}
			<tr>
				<td>{^{:user_id}} <input type="hidden" name="user[]" data-link="value{:user_id}"></td>
				<td>{^{:name}}</td>
				<td>{^{:phone}}</td>
			</tr>
		{{/for}}
		</tbody>
		
	</table>
</script>

<?php 
$loaderImg = $this->url->get('js/linkagesel/images/ui-anim_basic_16x16.gif');
$search_url = $this->url->get($module.'/i_user/search');

$this->assets->js['foot'][] = <<<EOT
raw::
var search_url = '$search_url';
var user = {
	user_id:null,
	name:null,
	phone:null
};

var chosenData = {
	list:[],
};

$(function(){

	$('#couponForm').submit(function(){
		
		if($('input[name="coupon_name"]').val().length==0){
			errorMsg('必须输入说明');
			return false;
		}
		if(isNaN($('input[name="amount"]').val())){
			errorMsg('代金券金额必须为有效数字');
			return false;
		}
		if($('input[name="min_limit"]').val().length>0 && isNaN($('input[name="min_limit"]').val())){
			errorMsg('使用限制必须为有效数字');
			return false;
		}
	});

	displayChosenData();

    $('.date-picker').datepicker({
    	dateFormat:'yy-mm-dd',
		autoclose: true,
		todayHighlight: true,
	});

	$('#specialUsers').change(function(){
		if(this.checked){
			$.each($('input[name="level[]"]'),function(i,o){
				o.checked = false;
			});

			$('#specialUsersBox').show();
		}
	});

	$('input[name="level[]"]').change(function(){
		if(this.checked){
			if(chosenData.list.length>0){
				layer.confirm("切换为指定用户等级后，将清空您已经手动选择的发放会员，确定要执行吗？",function(index){
					$('#specialUsers').attr('checked',false);
					$.observable(chosenData).setProperty('list',[]);
					layer.close(index);
				});
			}
			else{
				$('#specialUsers').attr('checked',false);
				$.observable(chosenData).setProperty('list',[]);
			}
			$('#specialUsersBox').hide();
		}
	});

	
	$('#chooseUserBtn').click(function(){
		var dialog = \$('#searchFormContainer').dialog({
            modal:true,
            title:"<div class='widget-header widget-header-small'><h4 class='smaller'><i class='ace-icon fa fa-check'></i> 选择用户</h4></div>",
            title_html:true,
            width:700,
            height:'auto',
            position:{ my: "center top+10%", at: "center top+10%", of:window },
            buttons:[
            	{
                    text: "选择完成",
                    "class" : "btn btn-xs btn-success",
                    click: function() {
                    	console.log(user.user_id);
                    	var has_chosen = 0;
                    	$.each($('input[name="user[]"]'),function(i,o){
                    		if(user.user_id==$(o).val()){
								has_chosen = 1;
								return false;
							}
                    	});
      
                    	if(has_chosen){
							errorMsg('此用户已经被选择过了');
                    	}
                    	else{
                    		$('input[name="user"]:checked').parentsUntil('tr').hide();
	                    	$.observable(chosenData.list).insert(user);  
	                        $(this).dialog( "close" ); 
                    	}
                    	
                    } 
                },
                {
                    text: "关闭",
                    "class" : "btn btn-xs",
                    click: function() {
                        $( this ).dialog( "close" ); 
                    } 
                },
                
            ]

        });
        getList(search_url, 1, getSearchParams());
	});

	$('#searchForm').submit(function(){
		console.log(search_url);
		getList(search_url, 1, getSearchParams());
		return false;
	});
});

//选中一条
var bindUserRadio = function(){
	$('input[name="user"]').change(function(){
		if(this.checked){
			user.user_id = $(this).val();
			user.name = $(this).parentsUntil('tbody').find('td:eq(2)').text();
			user.phone = $(this).parentsUntil('tbody').find('td:eq(3)').text();
			// console.log(user);
		}
		else{

			user.user_id = null;
			user.name = null,
			user.phone = null;
		}
	});
}

var getSearchParams = function(){
	var params = {
		level_id:$('#searchForm [name="level_id"]').val(),
		email:$('#searchForm input[name="email"]').val(),
		phone:$('#searchForm input[name="phone"]').val()
	}
	return params;
}

var getList = function (url,p,params){
    console.log(params);
    var searchParams = {};
    for(var k in params){
        searchParams[k] = params[k] ? params[k] : '';
    }

    p = p ? p : 1;
    searchParams['p'] = p;
    // console.log(searchParams);
    $.get(url+'?'+Math.random(),searchParams,function(result){
        console.log('listing');
        var tpl = $.templates("#spuList"); 
        tpl.link("#spuListContainer", result.data);
        
        bindUserRadio();

    });    
}


var displayChosenData = function(){
	
	var tpl = $.templates("#chosenUserList"); 
    tpl.link("#chosenUserListContainer", chosenData);
}
EOT;
 ?>
