<?php
use Common\Models\ICategory;
use Common\Models\IAd;
use Common\Models\IGoodsSpu as Spu;
use Phalcon\Tag;

?>
<div class="widget-box">
	
	<div class="widget-body">
		<div class="widget-main">
			<form class="form-horizontal" id="form" role="form" method="post" action="<?=$this->url->get($base_url.'/update')?>"  enctype="multipart/form-data">
				<input type="hidden" id="" name="shop_id" value="<?=$M->shop_id?>">
				
				<?php if($conf['enable_multi_shop']):?>
				<div class="form-group">
					<label class="col-sm-3 control-label no-padding-right" for=""><span class="required">*</span> 平台分类</label>

					<div class="col-sm-9">
						<div class="form-row">
							<select name="" id="selectSort"></select>
							<input type="hidden" id="sort_id" name="sort_id" value="">
						</div>
						
					</div>
				</div>
				<?php endif;?>

				<div class="form-group">
					<label class="col-sm-3 control-label no-padding-right" for=""><span class="required">*</span> <?=$M->getAttr('shop_name')?></label>

					<div class="col-sm-9">
						<input type="text" id="" name="shop_name" placeholder="" class="col-xs-10 col-sm-5" value="<?=$M->shop_name?>" />
					</div>
				</div>

				<div class="form-group">
					<label class="col-sm-3 control-label no-padding-right" for=""> <?=$M->getAttr('address')?></label>

					<div class="col-sm-9">
						<input type="text" id="" name="address" placeholder="" class="col-xs-10 col-sm-5" value="<?=$M->address?>" />
					</div>
				</div>

                <div class="form-group">
					<label class="col-sm-3 control-label no-padding-right" for=""> <?=$M->getAttr('lan')?></label>

					<div class="col-sm-9">
						<input type="text" id="" name="lan" placeholder="" class="col-xs-10 col-sm-5" value="<?=$M->lan?>" />
					</div>
				</div>

                <div class="form-group">
					<label class="col-sm-3 control-label no-padding-right" for=""> <?=$M->getAttr('lon')?></label>

					<div class="col-sm-9">
						<input type="text" id="" name="lon" placeholder="" class="col-xs-10 col-sm-5" value="<?=$M->lon?>" />
					</div>
				</div>

                <div class="form-group">
					<label class="col-sm-3 control-label no-padding-right" for=""> <?=$M->getAttr('postcode')?></label>

					<div class="col-sm-9">
						<input type="text" id="" name="postcode" placeholder="多个地区邮编请用英文逗号(,)隔开" class="col-xs-10 col-sm-5" value="<?=$M->postcode?>" />
					</div>
				</div>

				<div class="form-group">
					<label class="col-sm-3 control-label no-padding-right" for=""> <?=$M->getAttr('tel')?></label>

					<div class="col-sm-9">
						<input type="text" id="" name="tel" placeholder="" class="col-xs-10 col-sm-5" value="<?=$M->tel?>" />
					</div>
				</div>

				<div class="form-group">
					<label class="col-sm-3 control-label no-padding-right" for=""> <?=$M->getAttr('email')?></label>

					<div class="col-sm-9">
						<input type="text" id="" name="email" placeholder="" class="col-xs-10 col-sm-5" value="<?=$M->email?>" />
					</div>
				</div>

				<div class="form-group">
					<label class="col-sm-3 control-label no-padding-right" for=""> <?=$M->getAttr('logo')?></label>

					<div class="col-sm-9">
						<?php if($M->logo):?>
						<div class="thumb-list">
							<img class="thumb" src="<?=$M->logo?>" alt="">
						</div>
						
						<?php endif;?>
						<div class="row">
							<div class="col-sm-5">
								<input type="file" id="categoryCover" name="logo" class="input-file" value="<?=$M->getFmtLogo()?>" />
							</div>
						</div>
						
					</div>
				</div>

				<div class="form-group">
					<label class="col-sm-3 control-label no-padding-right" for=""> <?=$M->getAttr('bg')?></label>

					<div class="col-sm-9">
						<?php if($M->bg):?>
						<div class="thumb-list">
							<img class="thumb" src="<?=$M->bg?>" alt="">
						</div>
						
						<?php endif;?>
						<div class="row">
							<div class="col-sm-5">
								<input type="file" id="categoryCover" name="bg" class="input-file" value="<?=$M->getFmtBg()?>" />
							</div>
						</div>
						
					</div>
				</div>

				<div class="form-group">
					<label class="col-sm-3 control-label no-padding-right" for=""><span class="required">*</span> <?=$M->getAttr('intro')?></label>

					<div class="col-sm-9">
						<textarea name="intro" id="" rows="5" class="col-md-10"><?=$M->intro?></textarea>
					</div>
				</div>

				<div class="clearfix form-actions">
					<div class="col-md-offset-4 col-md-8">
						<button class="btn btn-info" type="submit">						
						<i class="ace-icon fa fa-check bigger-110"></i>
						提交
						</button>						
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
<?php
$this->assets->js['foot'][] = 'inc::'.$this->url->getStatic($this->url->get('admin/data/getSorts',[]));
$this->assets->js['foot'][] = <<<EOT
raw::
$(function(){
	var sortSelect = new LinkageSel({
		data:sorts,
		select: '#selectSort',
		head:'选择平台分类',
		minWidth:80,
		autoLink:false,
		loaderImg:false,
		defVal:[$def_sort]
	});

	sortSelect.onChange(function(){
		$('#sort_id').val(sortSelect.getSelectedValue());
	});
})
EOT;
?>