<?php
use Common\Models\IUserLevel;
use Phalcon\Tag;
?>
<div class="widget-box">
	
	<div class="widget-body">
		<div class="widget-main">
			<form class="form-horizontal ajax-form" role="form" id="update" method="post" action="<?=$this->url->get($base_url.'/'.($M->level_id?'update':'create'))?>">
				<input type="hidden" id="" name="level_id" value="<?=$M->level_id?>">

				
				<div class="form-group">
					<label class="col-sm-3 control-label no-padding-right" for=""><span class="required">*</span> <?=$M->getAttr('level_name')?></label>

					<div class="col-sm-9">
						<input type="text" id="" name="level_name" placeholder="" class="col-xs-10 col-sm-5" value="<?=$M->level_name?>" />
						<!-- <p><?=$M->level_name?></p> -->
					</div>
				</div>

				<div class="form-group">
					<label class="col-sm-3 control-label no-padding-right" for=""><span class="required">*</span> <?=$M->getAttr('price')?></label>

					<div class="col-sm-9">
						<input type="text" id="" name="price" placeholder="" class="col-xs-10 col-sm-5" value="<?=fmtMoney($M->price)?>" />
					</div>
				</div>

                <div class="form-group">

					<label class="col-sm-3 control-label no-padding-right" for=""> <?=$M->getAttr('discount_type')?></label>

					<div class="col-sm-9">
						<?php
						Tag::setDefault('discount_type',$M->discount_type);
						echo Tag::selectStatic([
							'discount_type',
							$M::getDiscountTypeContext(),
							'useEmpty'=>'true',
						]);
						?>
					</div>
				</div>

                <div class="form-group">
					<label class="col-sm-3 control-label no-padding-right" for=""><?=$M->getAttr('discount')?></label>

					<div class="col-sm-9">
						<input type="text" id="" name="discount" placeholder="" class="col-xs-10 col-sm-5" value="<?=$M->discount_type==1?fmtMoney($M->discount):$M->discount?>" />
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
<script type="text/javascript">
	$(function(){
		ajaxForm();
	});
</script>