<?php
use Common\Models\ServiceObject;
use Common\Models\Menu;
use Phalcon\Tag;
?>


<h3 class="header smaller lighter blue">文章</h3>
<span style=" position: absolute; right: 10px; margin-top: -53px; ">
	<form method="get" id="searchForm" action="<?=$this->url->get($module.'/'.$this->dispatcher->getControllerName().'/search')?>" class="form-inline">
        <?php
        Tag::setDefault('service_object_id',$vars['service_object_id']);
        echo Tag::select(array(
                "service_object_id",
                ServiceObject::find(),
                "using" => array("service_object_id", "name"),
                "useEmpty" => true
            ));
        ?>
        <select name="menu_id" id="menu_id">
            <option value="">选择栏目</option>
            <?php foreach($menus as $m):?>
            <option value="<?=$m->menu_id?>" <?php if($vars['menu_id']==$m->menu_id):?>selected<?php endif;?>><?=$m->menu_name?></option>
            <?php endforeach;?>
        </select>
        <select name="search">
            <option value="title" <?php if($vars['search']=='title'):?>selected<?php endif;?>>搜索标题</option>
            <option value="article_id" <?php if($vars['search']=='article_id'):?>selected<?php endif;?>>搜索ID</option>
            
        </select>
        
        <input type="text" name="search_keyword" class="input-small" placeholder="关键字" value="<?=$vars['search_keyword']?>" />
        <input type="hidden" name="id" value="<?=$vars['id']?>">
        <button id="searchBtn" type="submit" class="btn btn-info btn-sm">
            <i class="ace-icon fa fa-key bigger-110"></i>搜索
        </button>
	</form>
</span>

<div class="row" style="margin-bottom:10px; padding:0 10px">
    <table class="table table-striped table-bordered table-hover dataTable" id="unlinkTable">
   
        <?php foreach($page->items as $v):?>
        	<tr id="goods_<?=$v->article_id?>">
        		<td class="center"><?=$v->article_id?></td>
                <td><?=$v->title?></td>
                <td width="60">                
				
					<button class="btn btn-xs btn-danger selectBtn" data-id="<?=$v->article_id?>">
						<i class="ace-icon fa fa-unlink bigger-110"></i>
						选择
					</button>
                </td>
        	</tr>
        <?php endforeach;?>

    </table>
</div>

<div class="row">
    <div class="col-xs-12">
        <div class="dataTables_paginate paging_bootstrap">
            <ul class="pagination">
                <?php $vars['p'] = 1;?>
                <li class="prev <?php if($page->current<=1):?>disabled<?php endif;?>"><a href="<?php echo $this->url->get($this->module.'/'.$this->dispatcher->getControllerName().'/search',$vars)?>"><i class="fa fa-angle-double-left"></i></a></li>
                <?php $vars['p'] = $page->current-1 ?>
                <li class="prev <?php if($page->current<=1):?>disabled<?php endif;?>"><a href="<?php echo $this->url->get($this->module.'/'.$this->dispatcher->getControllerName().'/search',$vars)?>"><i class="fa fa-angle-left"></i></a></li>
                <?php
                $num = 3;
                if($page->current-$num<=1){
                    $start = 1 ;
                }
                else{
                    $start = $page->current - $num;
                }

                if($page->current+$num>=$page->total_pages){
                    $end = $page->total_pages;
                }
                else{
                    $end = $page->current + $num;
                }

                $p = $start;
                $vars = $this->view->vars;
                while($p<=$end){
                    $vars['p'] = $p;
                ?>
                <li class="<?php if($page->current==$p):?>active<?php endif;?>"><a href="<?php echo $this->url->get($this->module.'/'.$this->dispatcher->getControllerName().'/search',$vars)?>"><?=$p?></a></li>
                <?php
                    $p++;
                }
                ?>
                <?php $vars['p'] = $page->current+1;?>
                <li class="next"><a href="<?php echo $this->url->get($this->module.'/'.$this->dispatcher->getControllerName().'/search',$vars)?>"><i class="fa fa-angle-right"></i></a></li>
                <?php $vars['p'] = $page->total_pages;?>
                <li class="next"><a href="<?php echo $this->url->get($this->module.'/'.$this->dispatcher->getControllerName().'/search',$vars)?>"><i class="fa fa-angle-double-right"></i></a></li>
            </ul>
        </div>
    </div>
</div>

<script type="text/javascript">
	$(function(){

		$('.pagination li a').click(function(){
			$.get($(this).attr('href'),function(result){
				$('#container').html(result.data);
			})
			return false;
		});

		$('#searchForm').submit(function(){
			$.get($(this).attr('action'),$(this).serialize(),function(result){
				$('#container').html(result.data);
			})
			return false;
		});

        $('.selectBtn').click(function(){
            var id = $(this).parent().parent().find('td:eq(0)').html();
            var name = $(this).parent().parent().find('td:eq(1)').html();
            $('#selectedArticle', parent.document).show();
            $('#selectedArticle .pull-left', parent.document).html('['+id+']'+name);
            $('#article_id', parent.document).val(id);
        });

        $('#service_object_id').change(function(result){
            $.get('<?=$this->url->get($module.'/menu/getList')?>',{service_object_id:$('#service_object_id').val()},function(result){
                var options = '';
                $.each(result.data,function(i,n){
                    options += '<option value="'+n.menu_id+'">'+n.menu_name+'</option>';
                })
                $('#menu_id').append(options);
            });
        });
	})
</script>