<?php
use Common\Models\ILabel;
use Phalcon\Tag;
?>
<div class="widget-box">
	
	<div class="widget-body">
		<div class="widget-main">
			<form class="form-horizontal ajax-form" role="form" id="update" method="post" action="<?=$this->url->get($base_url.'/'.($M->express_corp_id?'update':'create'))?>">
				<input type="hidden" id="" name="express_corp_id" value="<?=$M->express_corp_id?>">

				
				<div class="form-group">
					<label class="col-sm-3 control-label no-padding-right" for=""><span class="required">*</span> <?=$M->getAttr('corp_name')?></label>

					<div class="col-sm-9">
						<input type="text" id="" name="corp_name" placeholder="" class="col-xs-10 col-sm-5" value="<?=$M->corp_name?>" />
					</div>
				</div>

				
			</form>
		</div>
	</div>
</div>
<script type="text/javascript">
	$(function(){
		ajaxForm();
	});
</script>