<?php 
use Phalcon\Tag;
use Common\Components\Widgets\Grid;
use Common\Models\ILabel;
 ?>


<div class="row">
    <div class="col-xs-12" style="text-align: right">
        <form id="search" action="<?=$this->url->get($base_url.'/index')?>" class="form-inline">
           
            <button id="addBtn" type="button" class="btn btn-success btn-sm addBtn" ajax="<?=$this->url->get($base_url.'/create')?>">
            <i class="ace-icon fa fa-plus bigger-110"></i>新增
        </button>
        </form>
    </div>
    <div class="col-xs-12">
    <?php
    $grid = new Grid;
    $grid->run(array(
        'cols'=>[
            [ILabel::getAttr('corp_name'),'corp_name'],
        ],
        'buttons'=>['update','delete'],
        'buttonsCfg'=>[],
        'page'=>$page,
        ));
    ?>

    </div>
</div>

