<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
		<meta charset="utf-8" />
		<title>云导览系统登录</title>

		<meta name="description" content="User login page" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />

		<!-- bootstrap & fontawesome -->
		<link rel="stylesheet" href="<?=$config->application->basePath?>back/css/bootstrap.min.css" />
		<link rel="stylesheet" href="<?=$config->application->basePath?>back/css/font-awesome.min.css" />

		<!-- text fonts -->
		<link rel="stylesheet" href="<?=$config->application->basePath?>back/css/ace-fonts.css" />

		<!-- ace styles -->
		<link rel="stylesheet" href="<?=$config->application->basePath?>back/css/ace.min.css" />

		<!--[if lte IE 9]>
			<link rel="stylesheet" href="<?=$config->application->basePath?>back/css/ace-part2.min.css" />
		<![endif]-->
		<link rel="stylesheet" href="<?=$config->application->basePath?>back/css/ace-rtl.min.css" />

		<!--[if lte IE 9]>
		  <link rel="stylesheet" href="<?=$config->application->basePath?>back/css/ace-ie.min.css" />
		<![endif]-->
		<link rel="stylesheet" href="<?=$config->application->basePath?>back/css/ace.onpage-help.css" />
		<link rel="stylesheet" href="<?=$config->application->basePath?>back/css/my.css" />
		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->

		<!--[if lt IE 9]>
		<script src="<?=$config->application->basePath?>back/js/html5shiv.js"></script>
		<script src="<?=$config->application->basePath?>back/js/respond.min.js"></script>
		<![endif]-->
	</head>

	<body class="login-layout light-login">
		<div class="main-container">
			<div class="main-content">
				<?php echo $this->getContent() ?>
			</div><!-- /.main-content -->
		</div><!-- /.main-container -->


	</body>
</html>
