<div class="widget-box">
	

	<div class="widget-body">
		<div class="widget-main">
			<form class="form-horizontal" role="form" id="update" method="post" action="<?=$this->url->get($basicUrl.'/update')?>" enctype="multipart/form-data">
				
				<div class="form-group">
					<label class="col-sm-2 control-label no-padding-right" for=""> 视频</label>

					<div class="col-sm-10">
						
						<div id="uploader" class="wu-example">
						    <!--用来存放文件信息-->
						    <div id="fileList" class="uploader-list"></div>
						    <div class="btns">
						        <div id="picker" type="button">选择文件</div>
						        <button id="uploadVideBtn" type="button" class="btn btn-default">开始上传</button>
						    </div>
						</div>

					</div>
				</div>

				<div class="clearfix form-actions">
					<div class="col-md-offset-3 col-md-9">
						<button class="btn btn-info" type="submit">
						<i class="ace-icon fa fa-check bigger-110"></i>
						提交
						</button>
					
					</div>
				</div>
				
			</form>
		</div>
	</div>
</div>

<?php

//webuploader
$swf_url = $this->url->get('/webuploader/Uploader.swf');
$audio_url = $this->url->get('/admin/upload/video',["field_name"=>'file']);
$this->assets->css['head'][] = 'inc::webuploader/webuploader.css';
$this->assets->js['foot'][] = 'inc::webuploader/webuploader.min.js';
$this->assets->js['foot'][] = <<<EOT
raw::
\$(function(){

	var \$ = jQuery,
    \$list = \$('#fileList'),
    // 优化retina, 在retina下这个值是2
    ratio = window.devicePixelRatio || 1,

    // 缩略图大小
    thumbnailWidth = 100 * ratio,
    thumbnailHeight = 100 * ratio,

    // Web Uploader实例
    uploader;
	
	// 初始化Web Uploader
	uploader = WebUploader.create({

	    // 自动上传。
	    auto: false,

	    runtimeOrder:'html5',

	    // swf文件路径
	    swf: '$swf_url',

	    // 文件接收服务端。
	    server: '$audio_url',

	    // 选择文件的按钮。可选。
	    // 内部根据当前运行是创建，可能是input元素，也可能是flash.
	    pick: {
	    	id:"#picker",
	    	multiple:false
	    },

	    //fileNumLimit:1,

	    // 只允许选择文件，可选。
	    /*accept: {
	    	title: 'Images',
	    	extensions: 'gif,jpg,jpeg,bmp,png',
	    	mimeTypes: 'image/*'
	    }*/
  	});

  	$('#uploadVideBtn').click(function(){
  		console.log('start uploading...');
  		uploader.upload();
  	});


	// 当有文件添加进来的时候
	uploader.on( 'fileQueued', function( file ) {
		var \$li = \$(
        '<div id="' + file.id + '" class="img-item thumbnail">' +
          '<img>' +
          '<div class="info">' + file.name + '</div>' +
        '</div>'
        ),
		\$img = \$li.find('img');

    	//\$list.append( \$li );
    	\$list.html( \$li );

	    // 创建缩略图
	    uploader.makeThumb( file, function( error, src ) {
			if ( error ) {
			\$img.replaceWith('<span>不能预览</span>');
			return;
			}

	      	\$img.attr( 'src', src );
	    }, thumbnailWidth, thumbnailHeight );
  	});

	// 文件上传过程中创建进度条实时显示。
	uploader.on( 'uploadProgress', function( file, percentage ) {
		var \$li = \$( '#'+file.id ),
		  	\$percent = \$li.find('.progress span');

		// 避免重复创建
		if ( !\$percent.length ) {
		  \$percent = \$('<p class="progress"><span></span></p>')
		      .appendTo( \$li )
		      .find('span');
		}
		console.log(percentage);
		//\$percent.css( 'width', percentage * 100 + '%' );
		\$percent.css( 'width', 50 + '%' );
	});

	// 文件上传成功，给item添加成功class, 用样式标记上传成功。
	uploader.on( 'uploadSuccess', function( file ) {
		console.log('upload success');
		\$( '#'+file.id ).addClass('upload-state-done');
	});

	// 文件上传失败，现实上传出错。
	uploader.on( 'uploadError', function( file ) {
		console.log('upload error');
		var \$li = \$( '#'+file.id ),
		  	\$error = \$li.find('div.error');

		// 避免重复创建
		if ( !\$error.length ) {
		  	\$error = \$('<div class="error"></div>').appendTo( \$li );
		}

		\$error.text('上传失败');
	});

	// 完成上传完了，成功或者失败，先删除进度条。
	uploader.on( 'uploadComplete', function( file ) {
		console.log('upload complete');
		\$( '#'+file.id ).find('.progress').remove();
	});


});
EOT;
?>