<?php 
use Phalcon\Tag;
use Common\Components\Widgets\Grid;
use Common\Models\IAd;
use Common\Models\IAdPos;
 ?>

<?php foreach($list as $v):?>
<div class="row">
    <div class="col-xs-12">
        <div class="col-xs-4">
            <h5><?=$v['name']?></h5>
        </div>
        <div class="col-xs-8"  style="text-align: right">
            <form id="search" action="<?=$this->url->get($base_url.'/index')?>" class="form-inline">
            <?php if($v['num']):?>广告数量：<?=$v['ads']->total_items?> / <?=$v['num']?> <?php endif;?>
            <?php if($v['num']==0 || $v['ads']->total_items<$v['num']):?>
                <a class="btn btn-success btn-sm" href="<?=$this->url->get($base_url.'/create',['ad_pos_id'=>$v['ad_pos_id']])?>">
                    <i class="ace-icon fa fa-plus bigger-110"></i>新增
                </a>
            <?php endif;?>
            </form>
        </div>
        
    </div>
    <div class="col-xs-12">
    <?php
    $grid = new Grid;
    $grid->run(array(
        'cols'=>[
            [IAd::getAttr('ad_name'),'ad_name'],
            ['生效时间','{$o}->start_time."至".{$o}->end_time','function'],
            [IAd::getAttr('status'),'{$o}->getStatusContext({$o}->status)','function'],
        ],
        'buttons'=>['update','delete'],
        'buttonsCfg'=>[
            'update'=>[
                'type'=>'href'
            ]
        ],
        'page'=>$v['ads'],
        'hidePage'=>1,
        ));
    ?>

    </div>
</div>
<?php endforeach;?>
