<div class="widget-box">
	

	<div class="widget-body">
		<div class="widget-main">
			<form class="form-horizontal" role="form" id="update" method="post" action="<?=$this->url->get($base_url.'/changePassword')?>">
				<input type="hidden" id="update_id" name="id" value="">
				<div class="form-group">
					<label class="col-sm-3 control-label no-padding-right" for="update_username"> 帐号</label>

					<div class="col-sm-9">
						<input type="text" disabled="disabled" id="update_username" name="username" value="<?=$M->username?>" placeholder="" class="col-xs-10 col-sm-5" />
					</div>
				</div>

				<div class="form-group">
					<label class="col-sm-3 control-label no-padding-right" for=""><span class="required">*</span> 原密码</label>

					<div class="col-sm-9">
						<input type="password" id="" name="password" placeholder="" class="col-xs-10 col-sm-5" />
					</div>
				</div>

				<div class="form-group">
					<label class="col-sm-3 control-label no-padding-right" for=""><span class="required">*</span> 新密码</label>

					<div class="col-sm-9">
						<input type="password" id="" name="newpassword" placeholder="" class="col-xs-10 col-sm-5" />
					</div>
				</div>

				<div class="form-group">
					<label class="col-sm-3 control-label no-padding-right" for="update_repassword"><span class="required">*</span>  重复密码</label>

					<div class="col-sm-9">
						<input type="password" id="" name="repassword" placeholder="" class="col-xs-10 col-sm-5" />
					</div>
				</div>

				<div class="clearfix form-actions">
					<div class="col-md-offset-3 col-md-9">
						<button class="btn btn-info" type="submit">
						<i class="ace-icon fa fa-check bigger-110"></i>
						提交
						</button>
					
					</div>
				</div>
			</form>
		</div>
	</div>
</div>