<?php 
use Phalcon\Tag;
use Common\Models\StatDayOrder;
?>
<div>
    <div id="main" style="width: 100%;height:600px;"></div>     
</div>
<div class="row">
    <div class="col-xs-12" style="text-align: right">
        <form id="search" action="<?=$this->url->get($base_url.'/index')?>" class="form-inline">  
            订单日期:         
            <input type="text" name="start_day" placeholder="开始日期" class="input-small date-picker" value="<?=$vars['start_day']?>">   
            -
            <input type="text" name="end_day" placeholder="结束日期" class="input-small date-picker" value="<?=$vars['end_day']?>">         
       
            <button id="searchBtn" type="submit" class="btn btn-info btn-sm">
                <i class="ace-icon fa fa-key bigger-110"></i>搜索
            </button>
        </form>
    </div>
</div>

<div class="row">
    <div class="col-xs-12">
    <table class="table table-striped table-bordered table-hover dataTable">
        <thead>
            <tr>
                <th><?=StatDayOrder::getAttr('day')?></th>
                <th><?=StatDayOrder::getAttr('num')?></th>
                <th><?=StatDayOrder::getAttr('amount')?></th>
                <th><?=StatDayOrder::getAttr('per_amount')?></th>
            </tr>
        </thead>
        <tbody>
        <?php 
        $total_num = 0;
        $total_amount = 0;
        $per_amount = 0;
        $chart_days = [];
        $chart_nums = [];
        $chart_amounts = [];
        $chart_per_amounts = [];

        foreach($page->items as $Item):
            $total_num += $Item->num;
            $total_amount += $Item->amount;
            $chart_days[] = $Item->day;
            $chart_nums[] = $Item->num;
            $chart_amounts[] = fmtMoney($Item->amount);
            $chart_per_amounts[] = fmtMoney($Item->per_amount);
        ?>
            <tr>
                <td><?=$Item->day?></td>
                <td><?=$Item->num?></td>
                <td><?=fmtMoney($Item->amount)?></td>
                <td><?=fmtMoney($Item->per_amount)?></td> 
            </tr>
        <?php endforeach;?>
            <tr>
                <th>总计</th>
                <th><?=$total_num?></th>
                <th><?=fmtMoney($total_amount)?></th>
                <th><?=$total_num ? fmtMoney(round($total_amount/$total_num)) : '0.00'?></th>
            </tr>
        </tbody>
    </table>
    

    </div>
</div>
<script>
   
</script>
<?php
$chart_days = json_encode($chart_days);
$chart_nums = json_encode($chart_nums);
$chart_amounts = json_encode($chart_amounts);
$chart_per_amounts = json_encode($chart_per_amounts);

$this->assets->js['foot'][] = 'inc::js/echarts.common.min.js';
$this->assets->js['foot'][] = <<<EOT
raw::
$(function(){
    $('.date-picker').datepicker({
        dateFormat:'yy-mm-dd',
        autoclose: true,
        todayHighlight: true,
        maxDate:'+0 day'
    });
    
    $('#search').submit(function(){
        var start = $('input[name="start_day"]').val();
        var end = $('input[name="end_day"]').val();

        if(start){
            var start_day = start.split('-');
            var start_date = new Date(start_day[0],start_day[1],start_day[2]);
        }
        if(end){
            var end_day = end.split('-');
            var end_date = new Date(end_day[0],end_day[1],end_day[2]);
        }
        console.log(start_date);
        console.log(end_date);
        
        if(start_date && end_date){
            if(start_date>end_date){
                errorMsg("搜索的开始日期不能大于结束日期");
                return false;
            }
            
            if(end_date.getTime() - start_date.getTime() > 30*86400*1000){
                errorMsg("搜索的日期跨度不能超过30天");
                return false;
            }
        }
        
        
        
    });

    // 基于准备好的dom，初始化echarts实例
    var myChart = echarts.init(document.getElementById('main'));

    // 指定图表的配置项和数据
    var option = {
        title: {
            text: ''
        },
        tooltip: {},
        legend: {
            data:['订单量','订单金额','客单价']
        },
        xAxis: {
            data: $chart_days
        },
        yAxis: {},
        series: [
            {
                name: '订单量',
                type: 'bar',
                data: $chart_nums
            },
            {
                name: '订单金额',
                type: 'bar',
                data: $chart_amounts
            },
            {
                name: '客单价',
                type: 'bar',
                data: $chart_per_amounts
            }
        ]
    };

    // 使用刚指定的配置项和数据显示图表。
    myChart.setOption(option);
});
        
EOT;
?>