<?php
use Common\Models\IUser;
use Phalcon\Tag;
?>


<?php if($page):?>
<div class="row">
    <table class="table table-striped table-bordered table-hover dataTable" id="unlinkTable">
   
        <tbody id="userListContainer"></tbody>

    </table>
</div>
<div class="row">
    <div class="col-xs-12">
        <ul class="pagination" id="pageContainer"></ul>
    </div>
</div>

<?php endif;?>

<script id="dataList" type="text/x-jsrender">
{^{for list}}
    <tr>
      
        <td>{^{:name}}</td>
        <td>{^{:phone}}</td>
        <td>{^{:id_num}}</td>
        <td>
            <a data-link="href{:'#/edit/ClientUser/'+Id}">编辑</a>
            <a class="del-act" href="javascript:void(0)" data-type="clientUser"  data-link="data-id{:user_id}">删除</a>
            
        </td>
    </tr>
{{/for}}
</script>

<script type="text/javascript">
    var user_id = '<?=$selected_user_id?>';
    var search_url = '<?=$this->url->get($base_url.'/search')?>';
    var getList = function (url,p,params){
                
            var searchParams = {};
            for(var k in params){
                searchParams[k] = params[k] ? params[k] : '';
            }
        
            p = p ? p : 1;
            searchParams['PageIndex'] = p;
            // console.log(searchParams);
            $.get(api_url+'?'+Math.random(),searchParams,function(result){
                console.log('listing');
                var tpl = $.templates("#userList"); 
                tpl.link("#userListContainer", result.Data);
                  
                // delAct();            
                page(result.Data.TotalPages,p);

            });
            
        }

    var page = function(totalPages,page,group){
            totalPages = totalPages ? totalPages :1;
            page = page ? parseInt(page) :1;
            $('#pageContainer').twbsPagination('destroy');
            $('#pageContainer').twbsPagination({
                totalPages: totalPages,
                first:'首页',
                prev:'上一页',
                next:'下一页',
                last:'尾页',
                // totalPages:1,
                startPage:page,
                visiblePages: 7,
                initiateStartPageClick:false,
                onPageClick: function (event, page) {
                    // console.log('Page ' + page);
                    location.hash = group+'/'+page;
                    getList(api_url,page);
                }
            });
        }

	$(function(){

		$('.pagination li a').click(function(){
			$.get($(this).attr('href'),function(result){
				$('#container').html(result.data);
			})
			return false;
		});

		$('#searchForm').submit(function(){
			$.get($(this).attr('action'),$(this).serialize(),function(result){
				$('#container').html(result.data);
			})
			return false;
		});


        $('.selectBtn').click(function(){
            var id = $(this).parent().parent().find('td:eq(0)').html();
            var name = $(this).parent().parent().find('td:eq(1)').html();
            $('#selectedGift', parent.document).show();
            $('#selectedGift .pull-left', parent.document).html('['+id+']'+name);
            $('#user_id', parent.document).val(id);
            $('.selected-tag').html('');
            $('#selected_gift_'+id).html('已选择');
        });

        console.log(user_id);
        if(user_id){
            $('#selected_gift_'+user_id).html('已选择');
        }

        $('form').submit(function(){
            getList(search_url,1,$('form').serialize());
            return false;
        });
	})
</script>