<?php var_dump($jssdk_config)?>
<script src="http://res.wx.qq.com/open/js/jweixin-1.0.0.js"></script>
<script>

  wx.config({
    debug: true,
    appId: '<?=$jssdk_config["appId"];?>',
    timestamp: <?=$jssdk_config["timestamp"];?>,
    nonceStr: '<?=$jssdk_config["nonceStr"];?>',
    signature: '<?=$jssdk_config["signature"];?>',
    jsApiList: [
      // 所有要调用的 API 都要加到这个列表中
      'chooseImage'
    ]
  });
  wx.ready(function () {
    wx.chooseImage({
      count: 1, // 默认9
      sizeType: ['original', 'compressed'], // 可以指定是原图还是压缩图，默认二者都有
      sourceType: ['album', 'camera'], // 可以指定来源是相册还是相机，默认二者都有
      success: function (res) {
          var localIds = res.localIds; // 返回选定照片的本地ID列表，localId可以作为img标签的src属性显示图片
      }
  });
    
  });
</script>